openapi: 3.0.0
info:
  title: ms_mock
  version: 1.0.0
servers:
  - url: https://api.restful-api.dev
  - url: https://api.open-meteo.com
tags:
  - name: ejemplo1
  - name: ejemplo3
  - name: ejemplo2
paths:
  /objects:
    get:
      tags:
        - ejemplo1
      summary: ejemplo1
      parameters:
        - name: accept
          in: header
          schema:
            type: string
          example: >-
            text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /v1/forecast:
    get:
      tags:
        - ejemplo3
      summary: meteo
      parameters:
        - name: latitude
          in: query
          schema:
            type: number
          example: '52.52'
        - name: longitude
          in: query
          schema:
            type: number
          example: '13.41'
        - name: current
          in: query
          schema:
            type: string
          example: temperature_2m,wind_speed_10m
        - name: hourly
          in: query
          schema:
            type: string
          example: temperature_2m,relative_humidity_2m,wind_speed_10m
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
